class IndustryConstants():
    FACTORY_INDUSTRY_DICT = {
        "Banglian spandex": "Spandex", "Botai furniture manufactory": "Furniture manufactory",
        "Changhua Auto Parts Manufactory": "Auto Parts Manufactory", "Chunguang hardware factory": "Hardware factory",
        "Dadongfang furniture manufactory": "Furniture manufactory", "Dakang furniture manufactory": "Furniture manufactory",
        "Gengde electronic equipment factory": "Electrical appliance factory", "Gujia furniture factory": "Furniture manufactory",
        "Hengfeng paper mill": "Papermill", "Hengjiu Machinery": "Machinery", "Huahui Machinery": "Machinery",
        "Hebang brake pad manufactory": "Auto brake pad manufactory", "Liyuan hydroelectric": "Hydroelectric",
        "Longwei furniture manufactory": "Furniture manufactory", "Mamibao baby carriage manufactory": "Baby carriage manufactory",
        "NSK Precision Machinery Co., Ltd": "Machinery", "Runde wheel manufacturing": "Auto Parts Manufactory",
        "Waigaoqiao Shipyard": "Grid structure", "Songxia electrical appliance factory": "Electrical appliance factory",
        "Wanhao furniture factory": "Furniture manufactory", "Weixin Textile mill": "Textile mill",
        "Dongfeng Reno Co.": "Final assembly plant for automobiles", "Yufeng paper mill": "Papermill",
        "东风汽车悬架弹簧有限公司": "Auto Parts Manufactory", "东风汽车有限公司商用车车架厂": "Commercial vehicle body factory",
        "东风汽车有限公司商用车车身厂": "Commercial vehicle body factory", "东风汽车紧固件有限公司": "Automotive Fasteners",
        "东风汽车车轮有限公司": "Auto Parts Manufactory", "总装配厂": "Auto Parts Manufactory",
        "万达实耐宝": "Hardware factory", "东南网架": "Iron and steel plant", "中海金州管道有限公司": "Machinery",
        "浙江红旗机械有限公司": "Machinery", "杭州重汽发动机有限公司": "Heavy truck engine factory",
        "杭钢2011": "Iron and steel plant", "杭钢2012": "Iron and steel plant", "万通智控": "Auto Parts Manufactory",
        "东华链条厂": "Auto Parts Manufactory", "力达纺织": "Textile mill", "双子机械": "Machinery",
        "天地数码": "Electrical appliance factory", "春风动力": "Auto Parts Manufactory", "沃尔夫链条": "Auto Parts Manufactory",
        "春江": "Textile mill", "中国重汽": "Heavy truck engine factory", "中国重汽杭州动力": "Heavy truck engine factory",
        "永创智能": "Electrical appliance factory", "萧山丝化印染": "Textile mill"
    }
    WORK_TYPE_DICT = {
    "装配工":"Assemblyman", "装配":"Assemblyman", "Assembler":"Assemblyman", "挡车":"Knitter", "细纱挡车":"Knitter",
    "挡车工":"Knitter", "接头": "Piecer", "机修": "Mechanic", "机修工": "Mechanic", "修理": "Mechanic",
    "金工": "Mechanic", "细纱":"Weaver", "纺纱":"Weaver", "纺织业":"Weaver", "落纱":"Weaver",
    "拉纱":"Weaver", "搬纱":"Weaver", "摇纱工":"Weaver", "后纺":"Weaver", "拉布":"Weaver",
    "染色":"Weaver", "平缩":"Weaver", "配棉":"Preparing", "对样":"Preparing", "扫地":"Other",
    "搞卫生":"Other", "保全":"Other", "保养":"Other", "质检":"Other", "辅助工":"Other",
    "操作工":"Operator", "手装":"Operator", "冲压工":"Stamping", "冲工":"Stamping", "冲床":"Stamping",
    "冲床工":"Stamping", "冲压":"Stamping", "精冲":"Stamping", "数控":"Numerical control machine", "机器人操作工":"Numerical control machine",
    "焊工":"Spot welding", "焊接":"Spot welding", "电焊":"Spot welding", "电气焊":"Spot welding", "焊接工":"Spot welding",
    "电焊工":"Spot welding", "点焊工":"Spot welding", "Spot welding operator": "Spot welding", "无心磨":"Polishing", "抛光":"Polishing",
    "打磨":"Polishing", "清磨":"Polishing", "磨工":"Polishing", "研磨":"Polishing","抛光打磨":"Polishing","抛光打磨修毛刺":"Polishing",
    "抛丸":"Polishing","抛丸工": "Polishing","冷镦工":"Cold heading", "冷镦":"Cold heading",
    "热处理工":"Heat treatment", "热处理":"Heat treatment", "熔化":"Heat treatment", "化铁工":"Heat treatment", "电镀":"Electroplating",
    "电镀工":"Electroplating", "起重工":"Craneman", "涂布":"Coating", "Guning &Nailling": "Guning & Nailling", "Guning & nailing": "Guning & Nailling",
    "Guning &nailling": "Guning & Nailling", "Frame nailing": "Guning & Nailling", "Woodworker":"Woodworking", "Wooden support":"Woodworking", "炉前控制":"Furnace front controller",
    "造型工":"Modelling", "制芯工":"Coremaking", "轧钢":"Steel rolling", "钻孔":"Drilling", "精整":"Finishing",
    "精轧":"Finishing", "地面操作":"Operator", "操作":"Operator", "操纵工":"Operator", "地操工":"Operator",
    "地操2":"Operator", "热锯口操作":"Operator", "锻压": "Forging", "探伤":"Inspector", "成检":"Inspector",
    "检验":"Inspector", "离线检测":"Inspector", "挑选":"Inspector", "清洗": "Cleaning", "清洗工":"Cleaning", "清沙工": "Cleaning","清理工":"Cleaning",
    "清花":"Cleaning", "钳工":"Bench worker", "钳手":"Bench worker","油漆":"Painter", "喷漆":"Painter", "喷丸":"Painter", "喷塑": "Painter", "喷漆工": "Painter",
    "上料工": "Blanker", "上料": "Blanker", "数控仪表车": "Numerical control machine", "数控操作": "Numerical control machine", 
    "numerical control machone": "Numerical controal machine", "自动装芯":"Automatic", "自动线":"Automatic", "自动装芯":"Automatic",
    "自检":"Inspector", "氩弧焊":"Argon Welding", "氩焊工":"Argon Welding", "氩焊": "Argon Welding", "压装":"Fracturing", "压弯":"Fracturing",
    "压手":"Fracturing", "巡检":"Inspector", "铣工":"Miller", "铣边" :"Miller", "无心磨工":"Polishing", "涂装":"Coating", "涂敷":"Coating", "挑筒":"Picker",
    "挑片":"Picker", "挑管":"Picker", "天车工":"Craneman", "平头机":"End Facing Machine", "平头": "End Facing Machine", "平头机操作工":"End Facing Machine",
    "平头机组长":"End Facing Machine", "拼装":"Assemblyman", "铆头工":"Snapper","铆头":"Snapper","铆关":"Snapper","铆工":"Snapper", "毛样":"Galley Proof",
    "落片":"Falling off", "落布":"Falling off", "空压运行":"Air Pressure", "空压机运行工":"Air Pressure", "卷包耳":"Curly", "卷曲操作":"Curly", "精整、p4": "Finishing",
    "精梳": "Finishing", "检验员":"Inspector", "检查员":"Inspector", "加热炉":"Heat treatment", "加热工":"Heat treatment", "火焰矫正":"Heat treatment", 
    "焊装工":"Welding", "焊工组长":"Welding", "回丝":"Hard Waste", "回沙":"Sand Blowback", "回火":"Temper", "打印":"Printer", "打砂":"Sanding", "打沙":"Sanding",
    "打磨抛光":"Polishing", "打磨工":"Polishing","搓丝工":"Roller", "粗砂":"Sanding", "成品检验":"Inspector", "叉车":"Craneman", "叉车工":"Craneman", "叉车司机":"Craneman",
    "手磨":"Polising","自动车工":"Automatic Turnman","手检":"Inspector","汽车装配工":"Car Fitter", "机装":"Machinery Fitting", "机装工":"Machinery Fitting",
    "CO2保护焊": "CO2 welding", "车工":"Lathe Worker", "出样":"Sampler", "电工":"Electrician", "调试":"Debugger", "调试员": "Debugger", "滚丝工":"Thread Roller",
    "滚丝、搓丝工":"Thread Roller", "机械加工":"Machining"
    }